update air gap - helm3 template change in syntax
starting with helm 3 the flag --name was removed
https://helm.sh/docs/helm/helm_template/

# helm template ./rancher-2.5.7.tgz --output-dir . --name rancher
Error: unknown flag: --name

it should be used as an option:
# helm template rancher ./rancher-2.5.7.tgz --output-dir .