Adding helm init
Helm commands will not work if helm init has not been run first:
$ helm repo add jetstack https://charts.jetstack.io
Error: Couldn't load repositories file (/home/rancher/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)